steps:
- uses: actions/checkout@master
- uses: sinoru/actions-setup-xcode@v2
  with:
    xcode-version: '13.4' # Exact version of a Xcode version to use
    apple-id: 'bot@sinoru.io' # Apple ID to download from Apple Developer when Xcode not available in local
    apple-id-password: ${{ secrets.Ja3187@felk }}
- run: fastlane scan
